/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myTempCleaner.GUI;

import com.myTempCleaner.Cmds.batchCmd;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author A7madY911
 */

public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        
        initComponents();
        
        //Set Frame Style
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        //center the window
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        this.setLocation(x, y);  
        
    }
    
    //Create Cmd Object
    batchCmd cmdObj = new batchCmd();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        receivedImageLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DevNameLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        winTempFilesButton = new javax.swing.JButton();
        recycleBinButton = new javax.swing.JButton();
        userTempFilesButton = new javax.swing.JButton();
        allUsersTempButton = new javax.swing.JButton();
        prefetchFilesButton = new javax.swing.JButton();
        historyFilesButton = new javax.swing.JButton();
        cookiesFilesButton = new javax.swing.JButton();
        cleanAllButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("myTempCleaner v1.0");
        setName("MainView");
        setResizable(false);

        receivedImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myTempCleaner/GUI/icon.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("myTempCleaner");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("Windows Temporary Files Cleaner");

        DevNameLabel.setBackground(getBackground());
        DevNameLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        DevNameLabel.setForeground(getForeground());
        DevNameLabel.setText("By A7madY911");
        DevNameLabel.setToolTipText("A7madY911@Gmail.com");
        DevNameLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DevNameLabel.setEnabled(false);
        DevNameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DevNameLabelMouseClicked(evt);
            }
        });

        jPanel1.setBackground(getBackground());
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        winTempFilesButton.setText("Win Temp");
        winTempFilesButton.setMaximumSize(new java.awt.Dimension(82, 23));
        winTempFilesButton.setMinimumSize(new java.awt.Dimension(82, 23));
        winTempFilesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                winTempFilesButtonMouseClicked(evt);
            }
        });

        recycleBinButton.setText("Recycle Bin");
        recycleBinButton.setMaximumSize(new java.awt.Dimension(82, 23));
        recycleBinButton.setMinimumSize(new java.awt.Dimension(82, 23));
        recycleBinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recycleBinButtonMouseClicked(evt);
            }
        });

        userTempFilesButton.setText("User Temp");
        userTempFilesButton.setMaximumSize(new java.awt.Dimension(82, 23));
        userTempFilesButton.setMinimumSize(new java.awt.Dimension(82, 23));
        userTempFilesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTempFilesButtonMouseClicked(evt);
            }
        });

        allUsersTempButton.setText("All Users");
        allUsersTempButton.setMaximumSize(new java.awt.Dimension(82, 23));
        allUsersTempButton.setMinimumSize(new java.awt.Dimension(82, 23));
        allUsersTempButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allUsersTempButtonMouseClicked(evt);
            }
        });

        prefetchFilesButton.setText("Prefetch");
        prefetchFilesButton.setMaximumSize(new java.awt.Dimension(82, 23));
        prefetchFilesButton.setMinimumSize(new java.awt.Dimension(82, 23));
        prefetchFilesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prefetchFilesButtonMouseClicked(evt);
            }
        });

        historyFilesButton.setText("History");
        historyFilesButton.setMaximumSize(new java.awt.Dimension(82, 23));
        historyFilesButton.setMinimumSize(new java.awt.Dimension(82, 23));
        historyFilesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyFilesButtonMouseClicked(evt);
            }
        });

        cookiesFilesButton.setText("Cookies");
        cookiesFilesButton.setMaximumSize(new java.awt.Dimension(82, 23));
        cookiesFilesButton.setMinimumSize(new java.awt.Dimension(82, 23));
        cookiesFilesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cookiesFilesButtonMouseClicked(evt);
            }
        });

        cleanAllButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cleanAllButton.setText("Clean All");
        cleanAllButton.setMaximumSize(new java.awt.Dimension(82, 23));
        cleanAllButton.setMinimumSize(new java.awt.Dimension(82, 23));
        cleanAllButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cleanAllButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(winTempFilesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(allUsersTempButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prefetchFilesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recycleBinButton, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(userTempFilesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(historyFilesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cookiesFilesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cleanAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(winTempFilesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userTempFilesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(historyFilesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allUsersTempButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(prefetchFilesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recycleBinButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cleanAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cookiesFilesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DevNameLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(receivedImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(receivedImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DevNameLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DevNameLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DevNameLabelMouseClicked
        String DevURL = "https://github.com/A7madY911";
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + DevURL);
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DevNameLabelMouseClicked

    private void winTempFilesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_winTempFilesButtonMouseClicked
        try {
            cmdObj.WinTempFilesBatchCmd();
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Please contact the developer :)", "Error!", JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_winTempFilesButtonMouseClicked

    private void cleanAllButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanAllButtonMouseClicked
        JOptionPane.showMessageDialog(null, "This function is not available in this version");
    }//GEN-LAST:event_cleanAllButtonMouseClicked

    private void userTempFilesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTempFilesButtonMouseClicked
        try {
            cmdObj.UserTempFilesBatchCmd();
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Please contact the developer :)", "Error!", JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_userTempFilesButtonMouseClicked

    private void allUsersTempButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allUsersTempButtonMouseClicked
        JOptionPane.showMessageDialog(null, "This function is not available in this version");
    }//GEN-LAST:event_allUsersTempButtonMouseClicked

    private void historyFilesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyFilesButtonMouseClicked
        try {
            cmdObj.HistoryFilesBatchCmd();
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Please contact the developer :)", "Error!", JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_historyFilesButtonMouseClicked

    private void prefetchFilesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prefetchFilesButtonMouseClicked
        try {
            cmdObj.PrefetchFilesBatchCmd();
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Please contact the developer :)", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_prefetchFilesButtonMouseClicked

    private void cookiesFilesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cookiesFilesButtonMouseClicked
        try {
            cmdObj.CookiesFilesBatchCmd();
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Please contact the developer :)", "Error!", JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_cookiesFilesButtonMouseClicked

    private void recycleBinButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recycleBinButtonMouseClicked
        try {
            cmdObj.RecycleBinBatchCmd();
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Please contact the developer :)", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_recycleBinButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DevNameLabel;
    private javax.swing.JButton allUsersTempButton;
    private javax.swing.JButton cleanAllButton;
    private javax.swing.JButton cookiesFilesButton;
    private javax.swing.JButton historyFilesButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton prefetchFilesButton;
    private javax.swing.JLabel receivedImageLabel;
    private javax.swing.JButton recycleBinButton;
    private javax.swing.JButton userTempFilesButton;
    private javax.swing.JButton winTempFilesButton;
    // End of variables declaration//GEN-END:variables
}
